export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS'
export const CLEAR_ALL_POKEMONS = 'CLEAR_ALL_POKEMONS'

export const SET_DETAIL_POKEMON = 'SET_DETAIL_POKEMON'
export const CLEAR_DETAIL_POKEMON = 'CLEAR_DETAIL_POKEMON'

export const GET_NAME_POKEMON = 'GET_NAME_POKEMON'

export const POST_POKEMON = 'POST_POKEMON'

// FILTERS
export const FILTER_BY_TYPES = 'FILTER_BY_TYPES'
export const ORDERING = 'ORDERING'